site_name: DjNRO
repo_url: https://github.com/grnet/djnro/
docs_dir: docs
site_author: DjNRO
theme: readthedocs
pages:
    - 'Introduction': 'index.md'
    - 'Installation':
        - 'Requirements': 'installation/requirements.md'
        - 'Installing DjNRO': 'installation/install.md'
        - 'Migrating from 0.8 to 1.0': 'installation/migrating-from-0.8-to-1.0.md'
        - 'Upgrading from 1.0 to 1.1': 'installation/upgrading-from-1.0.md'
        - 'Upgrading from 1.1 to 1.2': 'installation/upgrading-from-1.1.md'
        - 'Upgrading from 1.2 to 1.3': 'installation/upgrading-from-1.2.md'
